name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet tool restore
      - name: Paket install
        run: dotnet paket install
      - name: Build
        run: dotnet fake build -t Deploy
      - name: Test
        env:
          ABLY_TOKEN_TEST: ${{ secrets.ABLY_TOKEN_TEST }}
        run: dotnet fake build -t RunTests
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: deploy
